---

- name: "Service - Deploy systemd config to {{ deploy_service_systemd_location }}"
  become: true
  template:
    src: "{{ deploy_service_systemd_template }}"
    dest: "{{ deploy_service_systemd_location }}"

- name: "Service - Reload systemctl config"
  become: true
  systemd:
    daemon_reload: yes