---

- name: "Service - Deploy upstart config to {{ deploy_service_upstart_location }}"
  become: true
  template:
    src: "{{ deploy_service_upstart_template }}"
    dest: "{{ deploy_service_upstart_location }}"

- name: "Service - Reload initctl config"
  become: true
  command: /sbin/initctl reload-configuration